
import React from 'react';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
  type: 'privacy' | 'terms';
}

export const LegalModal: React.FC<LegalModalProps> = ({ isOpen, onClose, type }) => {
  if (!isOpen) return null;

  const title = type === 'privacy' ? 'Privacy Policy' : 'Terms of Service';
  
  return (
    <div className="fixed inset-0 bg-black bg-opacity-80 z-[60] flex items-center justify-center p-4 animate-fade-in">
      <div className="bg-slate-800 border border-slate-700 rounded-lg shadow-2xl w-full max-w-3xl max-h-[80vh] flex flex-col">
        <div className="p-4 border-b border-slate-700 flex justify-between items-center">
            <h2 className="text-xl font-bold text-white">{title}</h2>
            <button onClick={onClose} className="text-slate-400 hover:text-white">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
            </button>
        </div>
        <div className="p-6 overflow-y-auto text-slate-300 text-sm leading-relaxed space-y-4 custom-scrollbar">
            {type === 'privacy' ? (
                <>
                    <p><strong>1. Data Collection:</strong> We collect your name, email, phone number, and resume content specifically for the purpose of optimization and service delivery.</p>
                    <p><strong>2. AI Processing:</strong> Your resume data is processed by Google Gemini AI. We do not use your data to train public AI models.</p>
                    <p><strong>3. Data Retention:</strong> Your generated resumes are stored locally in your browser and in our secure simulated database. We enforce a strict "No Deletion" policy for legal compliance, but data can be suspended from view.</p>
                    <p><strong>4. Financial Data:</strong> All financial transaction logs are encrypted using AES-256 encryption before storage.</p>
                    <p><strong>5. Contact:</strong> For privacy concerns, contact support@atsoptimizer.com.</p>
                </>
            ) : (
                <>
                    <div className="bg-slate-900/50 p-4 rounded border border-yellow-600/30 mb-6">
                        <h3 className="text-yellow-400 font-bold mb-2 uppercase text-sm border-b border-yellow-600/30 pb-2">⚠️ AI-GENERATED CONTENT: AS-IS DISCLAIMER</h3>
                        <p className="mb-2">By registering and using this service, you acknowledge that all resume optimizations, ATS match scores, and derived content are generated by automated processes and Artificial Intelligence (AI).</p>
                        
                        <h4 className="text-white font-semibold mt-3">Waiver of Warranties</h4>
                        <p className="mb-2">The service and its outputs are provided "AS IS" and "AS AVAILABLE" without any warranties, express or implied, including fitness for a particular purpose or accuracy.</p>
                        
                        <h4 className="text-white font-semibold mt-3">Limitation of Liability</h4>
                        <p>We expressly disclaim any guarantee of employment, interviews, or the achievement of any specific success metric, including an ATS match score of 85% or higher. The developer is not liable for any damages, losses, or negative employment consequences resulting from your reliance on this application.</p>
                    </div>

                    <p><strong>1. Acceptance of Terms:</strong> By using ATS Resume Optimizer, you agree to these terms and the disclaimer above.</p>
                    <p><strong>2. Acceptable Use:</strong> You agree not to misuse the service, including generating resumes for individuals other than yourself (Identity Theft Protection).</p>
                    <p><strong>3. Subscription & Refunds:</strong> Subscriptions are billed as per the plan selected. Indian users are eligible for special renewal rates after 3 months.</p>
                    <p><strong>4. Termination:</strong> We reserve the right to suspend accounts found in breach of contract (e.g., excessive identity changes).</p>
                    <p><strong>5. Governing Law:</strong> These terms shall be governed by the laws of India.</p>
                </>
            )}
        </div>
        <div className="p-4 border-t border-slate-700 text-right">
            <button onClick={onClose} className="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded font-bold">Close</button>
        </div>
      </div>
    </div>
  );
};
