import React from 'react';

interface TermsOfServicePageProps {
  onBack: () => void;
}

export const TermsOfServicePage: React.FC<TermsOfServicePageProps> = ({ onBack }) => (
  <div className="min-h-screen bg-slate-950 text-slate-200 p-6 md:p-12">
    <main className="max-w-4xl mx-auto">
      <button onClick={onBack} className="text-emerald-400 hover:text-emerald-300 underline mb-8">Back to ScaleupResume</button>
      <h1 className="text-4xl font-bold text-white mb-3">Terms of Service</h1>
      <p className="text-slate-400 mb-10">Effective date: September 11, 2026</p>
      <div className="space-y-8 leading-relaxed text-slate-300">
        <section>
          <h2 className="text-2xl font-semibold text-white mb-3">AI-generated content</h2>
          <p>Resume optimizations, ATS match scores, and derived content are generated by automated processes and AI. The service is provided “AS IS” and “AS AVAILABLE” without warranties of accuracy, fitness for a particular purpose, or suitability for a specific hiring process.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold text-white mb-3">ATS Compatibility Disclaimer</h2>
          <p>Our service utilizes advanced formatting and keyword optimization designed to achieve an ATS compatibility score of 90% or higher based on the provided Job Description. However, Applicant Tracking Systems (ATS) vary widely by employer and software provider. We do not guarantee employment, interview invitations, or a flawless parse rate across all third-party systems.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold text-white mb-3">Subscription, fair use & cancellation</h2>
          <p>Premium subscription plans are billed monthly, quarterly, or semi-annually and automatically renew unless canceled prior to the next billing date. Users may cancel their subscription at any time through their account settings. We reserve the right to monitor account usage to prevent system abuse, including automated extraction, credential sharing, or use of the service to generate resumes for another person without authorization.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold text-white mb-3">Acceptance and liability</h2>
          <p>By using ScaleupResume, you agree to these terms. We do not guarantee employment, interviews, or any hiring outcome and are not liable for negative employment consequences resulting from reliance on generated content. We may suspend accounts that breach these terms. These terms are governed by the laws of India.</p>
        </section>
      </div>
    </main>
  </div>
);
